name: Python Application Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12.3'  
          cache: 'pip'  
          architecture: 'x64'  
          check-latest: true

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run Tests
      #   run: |
      #     pytest 

          
